/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import Classes.LocacoesCarros;
import Classes.ModeloTabela;
import controle.ConexaoBancodeDados;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author iangb
 */
public class GerenciarLocacoesCarros extends javax.swing.JFrame {
    
    private int id_carro;
    private int id_loca;

    ConexaoBancodeDados conex = new ConexaoBancodeDados();
    LocacoesCarros carro = new LocacoesCarros();
    
    /**
     * Creates new form GerenciarLocacoes
     */
    public GerenciarLocacoesCarros() {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldPesquisar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEncerrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLocacoes = new javax.swing.JTable();
        jTextFieldObservacoes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("GERENCIAR PEDIDOS DE CARROS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldPesquisar.setText("Buscar por Cliente");
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEncerrar.setText("Encerrar ");
        jButtonEncerrar.setEnabled(false);
        jButtonEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncerrarActionPerformed(evt);
            }
        });

        jTableLocacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLocacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLocacoesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableLocacoes);

        jTextFieldObservacoes.setEnabled(false);

        jLabel6.setText("Observações:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldObservacoes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(783, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    protected void atualizarTabela(){
        preencherTabela("select *from locacao_carro inner join cliente on id_cliente=id_client inner join carro on id_carro=id_car");
    }
    
    private void preencherTabela(String sql){
        
        ArrayList locacoes = new ArrayList();
        String [] colunas = new String [] {"ID","Cliente","Modelo","Placa","Data da Locação","Data de Entrega","Dias de Locação","Total (R$)", "Locação"};
        conex.conexao();
        conex.executaSql(sql);
        
        try {
            conex.rs.first();
            do{
                locacoes.add(new Object[] {conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getString("modelo"),conex.rs.getString("placa"),conex.rs.getString("data_inicio"),conex.rs.getString("data_termino"),conex.rs.getString("dias"),conex.rs.getString("valor"),conex.rs.getString("situacao")});
            }while(conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane,"Busque por um nova locação para preencher a tabela.");
        }
        ModeloTabela modelo = new ModeloTabela(locacoes, colunas);
        jTableLocacoes.setModel(modelo);
        
        //Tamanho das colunas na tabela
      
        jTableLocacoes.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableLocacoes.getColumnModel().getColumn(0).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(1).setPreferredWidth(185);
        jTableLocacoes.getColumnModel().getColumn(1).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTableLocacoes.getColumnModel().getColumn(2).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableLocacoes.getColumnModel().getColumn(3).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTableLocacoes.getColumnModel().getColumn(4).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(5).setPreferredWidth(110);
        jTableLocacoes.getColumnModel().getColumn(5).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableLocacoes.getColumnModel().getColumn(6).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableLocacoes.getColumnModel().getColumn(6).setResizable(false);
        jTableLocacoes.getColumnModel().getColumn(6).setPreferredWidth(180);
        jTableLocacoes.getColumnModel().getColumn(6).setResizable(false);
        
        jTableLocacoes.getTableHeader().setReorderingAllowed(false);
        jTableLocacoes.setAutoResizeMode(jTableLocacoes.AUTO_RESIZE_OFF);
        jTableLocacoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        
        preencherTabela("select *from locacao_carro inner join cliente on id_cliente=id_client inner join carro on id_carro=id_car where nome like'%" + jTextFieldBuscar.getText() + "%'");
        
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        int resposta = 0;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Excluir a Locação?");

        if (resposta == JOptionPane.YES_OPTION){
            
            carro.setCodModeloCarro(id_carro);
            carro.setLocacaoCod(id_loca);
            carro.alterarStatus(true);
            carro.excluir();
            preencherTabela("select *from locacao_carro inner join cliente on id_cliente=id_client inner join carro on id_carro=id_car");
            jButtonEncerrar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
        }
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncerrarActionPerformed
     
        int resposta = 0;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Encerrar a Locação? Essa operação não poderá ser revertida!");
        
        if (resposta == JOptionPane.YES_OPTION){
            carro.setCodModeloCarro(id_carro);
            carro.setLocacaoCod(id_loca);
            carro.alterarStatus(true);
            carro.alterarLocacao(false);
            JOptionPane.showMessageDialog(null, "Locação finalizada com sucesso!");
            preencherTabela("select *from locacao_carro inner join cliente on id_cliente=id_client inner join carro on id_carro=id_car");
        }
        
    }//GEN-LAST:event_jButtonEncerrarActionPerformed

    private void jTableLocacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLocacoesMouseClicked
        
        String loca = "" + jTableLocacoes.getValueAt(jTableLocacoes.getSelectedRow(), 0);
        conex.conexao();
        conex.executaSql("select *from locacao_carro inner join cliente on id_cliente=id_client where id='"+ loca +"'");
        
        try {
            conex.rs.first();
            jTextFieldBuscar.setText(conex.rs.getString("nome"));
            jTextFieldObservacoes.setText(conex.rs.getString("observacoes"));
            id_carro = conex.rs.getInt("id_carro");
            id_loca = conex.rs.getInt("id");
            jButtonEncerrar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            carro.setSituacao(conex.rs.getString("situacao"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro: " + ex);
        }
        
        if("Finalizada".equals(carro.getSituacao())){
            jButtonEncerrar.setEnabled(false);
        }
        
    }//GEN-LAST:event_jTableLocacoesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarLocacoesCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarLocacoesCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarLocacoesCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarLocacoesCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarLocacoesCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncerrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableLocacoes;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldObservacoes;
    private javax.swing.JButton jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
