/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import controle.ConexaoBancodeDados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author anderson
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBancodeDados conex = new ConexaoBancodeDados();
    
    CadastroUsuario telaUsu;// = new CadastroUsuario();
    CadastroFuncionario telaFunc;// = new CadastroFuncionario();
    CadastroCliente telaClie;// = new CadastroCliente();
    CadastroMoto telaMoto;// = new CadastroMoto();
    CadastroCarro telaCarro;// = new CadastroCarro();
    LocarCarro telaLocCarro;// = new LocarCarro();
    LocarMoto telaLocMoto;// = new LocarMoto();
    GerenciarLocacoesCarros telaGerLocCarro;//  = new GerenciarLocacoesCarros();
    GerenciarLocacoesMotos telaGerLocMoto;//  = new GerenciarLocacoesMotos();
    
    
    Date data = new Date();
    SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy"); // Instanciando obejto que formata a data
    String dataformatada = formatar.format(data);
    Timer timer;
    
    
    public TelaPrincipal(String usuario) {
        this.timer = new Timer(1000, new hora());
        timer.start();
        initComponents();
        jLabel2Data.setText(dataformatada);
        jLabelUsuario.setText(usuario);
        conex.conexao();
    }

    private TelaPrincipal() {
        this.timer = new Timer(1000, new hora());
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelU1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel2Data = new javax.swing.JLabel();
        jLabel3Relogio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLocacao = new javax.swing.JMenu();
        jMenuItemLocarCarro = new javax.swing.JMenuItem();
        jMenuItemLocarMoto = new javax.swing.JMenuItem();
        jMenuItemGerenciarLocacoesCarros = new javax.swing.JMenuItem();
        jMenuItemGerenciarLocacoesMoto = new javax.swing.JMenuItem();
        jMenu1Cadastros = new javax.swing.JMenu();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuItemCadFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadCarro = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemVoltarTalaInicial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelU1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelU1.setText("Usuário:");

        jLabelUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2Data.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3Relogio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelU1)
                .addGap(10, 10, 10)
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 606, Short.MAX_VALUE)
                .addComponent(jLabel2Data, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel3Relogio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelU1)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3Relogio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 620, 1200, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABRAAO\\Desktop\\imicial.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 1160, 590);

        jMenuLocacao.setText("Relatórios");

        jMenuItemLocarCarro.setText("Pacientes");
        jMenuItemLocarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocarCarroActionPerformed(evt);
            }
        });
        jMenuLocacao.add(jMenuItemLocarCarro);

        jMenuItemLocarMoto.setText("Médicos");
        jMenuItemLocarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocarMotoActionPerformed(evt);
            }
        });
        jMenuLocacao.add(jMenuItemLocarMoto);

        jMenuItemGerenciarLocacoesCarros.setText("Medicamentos");
        jMenuItemGerenciarLocacoesCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarLocacoesCarrosActionPerformed(evt);
            }
        });
        jMenuLocacao.add(jMenuItemGerenciarLocacoesCarros);

        jMenuItemGerenciarLocacoesMoto.setText("Equipamentos");
        jMenuItemGerenciarLocacoesMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarLocacoesMotoActionPerformed(evt);
            }
        });
        jMenuLocacao.add(jMenuItemGerenciarLocacoesMoto);

        jMenuBar1.add(jMenuLocacao);

        jMenu1Cadastros.setText("Cadastros");

        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenu1Cadastros.add(jMenuItemCadUsuarios);

        jMenuItemCadFuncionario.setText("Médicos/Pacientes");
        jMenuItemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionarioActionPerformed(evt);
            }
        });
        jMenu1Cadastros.add(jMenuItemCadFuncionario);

        jMenuItemCadCarro.setText("Equipamentos/Medicamentos");
        jMenuItemCadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadCarroActionPerformed(evt);
            }
        });
        jMenu1Cadastros.add(jMenuItemCadCarro);

        jMenuItem1.setText("Fornecedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1Cadastros.add(jMenuItem1);

        jMenuItem2.setText("Nota Fiscal");
        jMenu1Cadastros.add(jMenuItem2);

        jMenuBar1.add(jMenu1Cadastros);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuItemVoltarTalaInicial.setText("Voltar a tela inicial");
        jMenuItemVoltarTalaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVoltarTalaInicialActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemVoltarTalaInicial);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1206, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVoltarTalaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVoltarTalaInicialActionPerformed
        // TODO add your handling code here:
        TelaLogin telaLog = new TelaLogin();
        telaLog.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemVoltarTalaInicialActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        conex.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemLocarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocarMotoActionPerformed
       
        if(telaLocMoto == null)
            telaLocMoto = new LocarMoto();
        telaLocMoto.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemLocarMotoActionPerformed

    private void jMenuItemLocarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocarCarroActionPerformed
        
        if(telaLocCarro == null)
            telaLocCarro = new LocarCarro();        
        telaLocCarro.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemLocarCarroActionPerformed

    private void jMenuItemGerenciarLocacoesCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarLocacoesCarrosActionPerformed
        
        if(telaGerLocCarro == null)
            telaGerLocCarro = new GerenciarLocacoesCarros();
        telaGerLocCarro.setVisible(true);
        telaGerLocCarro.atualizarTabela();
        
    }//GEN-LAST:event_jMenuItemGerenciarLocacoesCarrosActionPerformed

    private void jMenuItemGerenciarLocacoesMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarLocacoesMotoActionPerformed

        if(telaGerLocMoto == null)
            telaGerLocMoto = new GerenciarLocacoesMotos();
        telaGerLocMoto.setVisible(true);
        telaGerLocMoto.atualizarTabela();
        
    }//GEN-LAST:event_jMenuItemGerenciarLocacoesMotoActionPerformed

    private void jMenuItemCadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadCarroActionPerformed
        if(telaCarro == null)
        telaCarro = new CadastroCarro();
        telaCarro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadCarroActionPerformed

    private void jMenuItemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionarioActionPerformed
        try {
            conex.executaSql("select *from usuario where nome='" + jLabelUsuario.getText() + "'");
            conex.rs.first();

            if(conex.rs.getString("tipo").equals("Administrador")){
                if(telaFunc == null)
                telaFunc = new CadastroFuncionario();
                telaFunc.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o Administrador do sistema.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o Administrador do sistema.");
        }
    }//GEN-LAST:event_jMenuItemCadFuncionarioActionPerformed

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed

        try {
            conex.executaSql("select *from usuario where nome='" + jLabelUsuario.getText() + "'");
            conex.rs.first();

            if(conex.rs.getString("tipo").equals("Administrador")){
                if(telaUsu == null)
                telaUsu = new CadastroUsuario();

                telaUsu.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o Administrador do sistema.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o Administrador do sistema.");
        }
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Data;
    private javax.swing.JLabel jLabel3Relogio;
    private javax.swing.JLabel jLabelU1;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1Cadastros;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCadCarro;
    private javax.swing.JMenuItem jMenuItemCadFuncionario;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemGerenciarLocacoesCarros;
    private javax.swing.JMenuItem jMenuItemGerenciarLocacoesMoto;
    private javax.swing.JMenuItem jMenuItemLocarCarro;
    private javax.swing.JMenuItem jMenuItemLocarMoto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVoltarTalaInicial;
    private javax.swing.JMenu jMenuLocacao;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


class hora implements ActionListener {
    @Override
    public void actionPerformed(ActionEvent e){
        Calendar now = Calendar.getInstance();
        jLabel3Relogio.setText(String.format("%1$tH:%1$tM:%1$tS",now));
    }
    
}

}


